# at top-level of prometheus.yml
rule_files:
  - "/etc/prometheus/alert_rules.yml"

# prometheus.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]


global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'flink'
    metrics_path: /metrics
    static_configs:
      - targets: ['flink-jobmanager:9450']

  - job_name: 'airflow-statsd'
    metrics_path: /metrics
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
