groups:
  - name: network_intrusion_detection
    rules:
      - alert: HighIntrusionRate
        expr: rate(intrusions_detected[5m]) > 10
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High intrusion detection rate"
          description: "Intrusion detection rate is {{ $value }} per second"

      - alert: FlinkJobDown
        expr: up{job="flink-jobmanager"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Flink JobManager is down"
          description: "Flink JobManager has been down for more than 1 minute"

      - alert: KafkaDown
        expr: up{job="kafka-exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kafka is down"
          description: "Kafka has been down for more than 1 minute"

      - alert: LowFlowProcessingRate
        expr: rate(total_flows_processed[5m]) < 1
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Low network flow processing rate"
          description: "Processing rate is {{ $value }} flows per second"

  - name: infrastructure_alerts
    rules:
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 90% for {{ $labels.instance }}"